Design home page
UgurCanTiryaki/ugur-web pull request #13
Opened 2021-08-08 10:17 UTC by UgurCanTiryaki

## Description

Home page is designed from scratch.

## Checklist

- [x] My changes are documented
- [x] My changes are tested

2021-08-08 11:03 UTC, MansurAliKoroglu requested changes

2021-08-08 11:03 UTC, MansurAliKoroglu commented on src/components/Home.vue
> +          <router-link to="/contact" class="">Contact</router-link>
If you put router links like that then user must click to the text. Button clicks won't work.

2021-08-08 15:22 UTC, UgurCanTiryaki commented on src/components/Home.vue
> +          <router-link to="/about" class="">Skills</router-link>
I don't know exact link for now. But I thought it could have `/about` as base Url. Anyways I could set it to `/about/skills` for now.

2021-08-10 07:34 UTC, MansurAliKoroglu commented on src/components/Home.vue
> +      >
I think that's still not fixed.

2021-08-10 07:50 UTC, MansurAliKoroglu approved these changes

2021-08-10 07:52 UTC, merged