Create footer
UgurCanTiryaki/ugur-web pull request #9
Opened 2021-07-29 10:28 UTC by UgurCanTiryaki

Footer component is created and implemented.

`Note`:

 When there is no component between header and footer, footer appears at the top of header. Home page was an example of this situation.

To solve this situation I thought I could:
- Make footer sticky
- Make sure there is always a component which has a height higher than header ( Header is absolute. As a page who has lower height than header will be located under the header, the remaining height of header ( remaining height = header's height - page component's height ) will be filled with footer ).

I used second one for home page and set it to h-screen for now. Please let me know if you have any suggestions.

2021-07-29 11:12 UTC, MansurAliKoroglu commented
I don't think you should do something about ooter appears under header problem because there will be content in pages that will push footer below.

2021-07-29 11:39 UTC, MansurAliKoroglu requested changes

2021-07-29 11:39 UTC, MansurAliKoroglu commented on package.json
> +    "@fortawesome/free-brands-svg-icons": "5.15.3",
Seems like a core package is missing or is there any reason to not install it? @fortawesome/fontawesome-svg-core

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/App.vue
> +    <Footer></Footer>
For here I suggest you to read https://v3.vuejs.org/style-guide/#self-closing-components-strongly-recommended It can be applied for Header as well.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Home.vue
> +  <p class="h-screen">
It's always good to indicate that these code here is just a temporary code with a `TODO:` comment.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +      flex flex-col
`flex-col` can go to it's own line.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +      text-white
For now we always used text-white. Maybe you should just make it global instead of typing it everywhere.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +};
You can also register globally I just checked documentation and seems that's the recommended way.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +  },
I really do not understand here. Could you please explain that?

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +      ></a>
You can also remove that if you are not planning adding your youtube channel soon. You can always add later.

2021-07-29 11:39 UTC, MansurAliKoroglu commented on src/components/Footer.vue
> +      <span class="w-1/5 text-center">ugurctiryaki@gmail.com</span>
This one can be also a `href` with `mailto`

2021-07-29 12:05 UTC, UgurCanTiryaki commented on package.json
> +    "@fortawesome/free-brands-svg-icons": "5.15.3",
There is an example in [vue-fontawesome](https://www.npmjs.com/package/@fortawesome/vue-fontawesome), which is under the `Alternative using component property` header, of using font awesome not globally but inside a component, and the core package you said is not used there. As my main intention for font awesome is to use it just for footer, so I implemented the example above. The package may never be used, therefore I didn't install it.

2021-07-29 12:13 UTC, UgurCanTiryaki commented on src/components/Footer.vue
> +      flex flex-col
This structure is what the code formatting in VSCode is structured. I didn't want to change it. But if you really suggest that, there is no problem in changing it.

2021-07-29 12:22 UTC, UgurCanTiryaki commented on src/components/Footer.vue
> +};
As I said above, I have no plan to using font awesome everywhere in the app. So I thought it could be better just registering it inside the component where I'm using it. But I have also doubts about not using the recommended way. Are you still suggesting registering globally?

2021-07-29 12:27 UTC, UgurCanTiryaki commented on src/components/Footer.vue
> +  },
I placed the icons, which are imported from font-awesome, to the component's state to reach and use them in the component. I used them within `FontAwesomeIcon` components as `icon` properties.

2021-08-06 11:27 UTC, MansurAliKoroglu approved these changes

2021-08-06 11:33 UTC, merged